// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmiEVMAan2gpSwfE-du5RtZK7EfWFUKmI',
    appId: '1:596605891115:web:8f66a0e0458dbe0a96706e',
    messagingSenderId: '596605891115',
    projectId: 'mobile-shop-management-deec8',
    authDomain: 'mobile-shop-management-deec8.firebaseapp.com',
    storageBucket: 'mobile-shop-management-deec8.firebasestorage.app',
    measurementId: 'G-JLEV0SW4HS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOyCuNpQP1Khya0MnU3i0FhQKxNoeORng',
    appId: '1:596605891115:ios:2f0ae8ec7ce6d20d96706e',
    messagingSenderId: '596605891115',
    projectId: 'mobile-shop-management-deec8',
    storageBucket: 'mobile-shop-management-deec8.firebasestorage.app',
    iosBundleId: 'com.example.mobileShopManagementSystem',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOyCuNpQP1Khya0MnU3i0FhQKxNoeORng',
    appId: '1:596605891115:ios:2f0ae8ec7ce6d20d96706e',
    messagingSenderId: '596605891115',
    projectId: 'mobile-shop-management-deec8',
    storageBucket: 'mobile-shop-management-deec8.firebasestorage.app',
    iosBundleId: 'com.example.mobileShopManagementSystem',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVcZE8XV1JMJq_6HpryoQ2jTBC9H62Svo',
    appId: '1:596605891115:android:d4feefc4dde5939396706e',
    messagingSenderId: '596605891115',
    projectId: 'mobile-shop-management-deec8',
    storageBucket: 'mobile-shop-management-deec8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmiEVMAan2gpSwfE-du5RtZK7EfWFUKmI',
    appId: '1:596605891115:web:f410ec523710c2a096706e',
    messagingSenderId: '596605891115',
    projectId: 'mobile-shop-management-deec8',
    authDomain: 'mobile-shop-management-deec8.firebaseapp.com',
    storageBucket: 'mobile-shop-management-deec8.firebasestorage.app',
    measurementId: 'G-M78LRK44PV',
  );

}